version: "3.8"

services:
  # Dịch vụ MySQL Database
  mysql_db:
    image: mysql:8.0
    container_name: mysql_bus_tracking
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ssb
    ports:
      - "3306:3306"
    volumes:
      # Map file .sql vào container
      - ./ssb.sql:/docker-entrypoint-initdb.d/ssb.sql
      # Tạo volume để lưu data
      - mysql_data:/var/lib/mysql

  # Dịch vụ Adminer để xem database
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mysql_db # Khởi động sau khi mysql_db chạy

# Định nghĩa volume
volumes:
  mysql_data: